---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: http
spec:
  http:
    endpoint: http://logging-operator-test-receiver:8080
    content_type: application/json
    buffer:
      type: memory
      tags: time
      timekey: 1s
      timekey_wait: 0s
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: silly-demo
spec:
  loki:
    url: http://loki:3100
    configure_kubernetes_labels: true
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: silly-demo
spec:
  match:
    - select:
        labels:
          app.kubernetes.io/name: silly-demo
  localOutputRefs:
    - http
    - silly-demo
