datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: loki
        type: loki
        url: http://loki:3100
        access: proxy
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.127.0.0.1.nip.io
